### ISSUE TITLE
Is any docker image for kafka-manager avaliable?

### ISSUE THREAD

**Issue by andy0301** [yahoo/kafka-manager#76]
We are going to use docker to install kafka-manager, but not sure if any docker image already available here, so that we can try leverage it in our installation? Another question is I found some image in docker site, but not sure right now the docker image how to manage the network between internal docker and external hosts? Because we have zookeeper setup in VMs using puppet, but try to use docker install kafka-manager, not sure will be any issues between network configuration?

**Comment by sheeley** [comment]
You can use sheepkiller/kafka-manager-docker (code is located here: https://github.com/sheepkiller/kafka-manager-docker). If you can connect to the zookeeper hosts outside of docker, it shouldn't be an issue to connect to them from within docker (and if you run into problems, you'll likely have better luck troubleshooting on a docker-specific forum rather than kafka-manager).

**Comment by stonefury** [comment]
Mine.

https://registry.hub.docker.com/u/stonefury/kafkamanager-docker/

<-----Original Message-----> 
>From: Johnny Sheeley [notifications@github.com]
>Sent: 6/4/2015 12:33:24 PM
>To: kafka-manager@noreply.github.com
>Subject: Re: [kafka-manager] Is any docker image for kafka-manager
avaliable? (#76)
>
>You can use sheepkiller/kafka-manager-docker (code is located here: 
>https://github.com/sheepkiller/kafka-manager-docker). If you can
connect to the zookeeper hosts 
>outside of docker, it shouldn't be an issue to connect to them from
within docker (and if you run into 
>problems, you'll likely have better luck troubleshooting on a
docker-specific forum rather than kafka-

**Comment by ebuildy** [comment]
No body had issue when running "sbt clean dist"? 

````
[info] Main Scala API documentation successful.
[info] Packaging /usr/local/kafka-manager/target/scala-2.11/kafka-manager_2.11-1.3.0.4-javadoc.jar ...
[info] Done packaging.
[error] File name too long
[error] one error found
[error] (compile:compileIncremental) Compilation failed
````

Because scala compiler can generate long file name that Docker AUFS not support.

**Comment by timmartin19** [comment]
@ebuildy I had the same issue.  Any luck in figuring it out?

**Comment by v-a** [comment]
@ebuildy / @timmartin19 I've been able to fix that adding a step in the Dockerfile to append 
`scalacOptions ++= Seq("-Xmax-classfile-name", "200")`
at the end of build.sbt in the main folder. 
This will tell scalac to not generate filenames longer than 200 char (AUFS compatible)

**Comment by timmartin19** [comment]
@v-a That is exactly how I ended up fixing the issue.  Thanks!

**Comment by rkettelerij** [comment]
There is now: https://hub.docker.com/r/kafkamanager/kafka-manager/tags introduced in https://github.com/yahoo/kafka-manager/pull/582

**Comment by vishwakulkarni** [comment]
If you want to deploy on cloudfoundry and manage kafka instance in cloudfoundry space, you can use this https://cloud.docker.com/u/vishykulk/repository/docker/vishykulk/kafka-manager, just bind your kafka instance to this and restage this application. it will work like a charm.

**Comment by lazystone** [comment]
Where new images will be published after the project name change?

I can't find version 3.0.0.0 in https://hub.docker.com/r/kafkamanager/kafka-manager/tags

**Comment by theturtle32** [comment]
Version 3.0.0.4 is up:
https://hub.docker.com/layers/kafkamanager/kafka-manager/3.0.0.4/images/sha256-6098a48d0beeaccebb59e36dff66f37bd160e6e1aed9592266b85bc0ed785f68?context=explore
